In this lab we will experiment with some of the deep learning concepts covered in the async material, and beyond. 

In [ ]:
# Import necessary packages. 
import torch, torch.nn as nn
from PIL import Image
torch.manual_seed(1)

### MSE Loss

In [ ]:
ypred = torch.arange(-5, 5).float()
yact = torch.randint(2, (len(ypred),)).float()
print(f'Dummy predicted values : {ypred}')
print(f'Dummy actual values : {yact}')

Dummy predicted values : tensor([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])
Dummy actual values : tensor([1., 1., 0., 0., 1., 1., 1., 1., 1., 0.])


In [ ]:
criterion = torch.nn.MSELoss(reduction='none')
loss = criterion(ypred, yact)
print(f'MSE loss for each element {loss}')
criterion = torch.nn.MSELoss(reduction='mean')
loss = criterion(ypred, yact)
print(f'MSE loss averaged {loss:.5f}')

MSE loss for each element tensor([36., 25.,  9.,  4.,  4.,  1.,  0.,  1.,  4., 16.])
MSE loss averaged 10.00000


### Binary Cross Entropy Loss

In [ ]:
ypred = torch.rand(10).float()
yact = torch.randint(2, (len(ypred),)).float()
print(f'Dummy predicted values : {ypred}')
print(f'Dummy actual values : {yact}')

Dummy predicted values : tensor([0.6387, 0.5247, 0.6826, 0.3051, 0.4635, 0.4550, 0.5725, 0.4980, 0.9371,
        0.6556])
Dummy actual values : tensor([0., 1., 0., 0., 1., 0., 0., 0., 1., 0.])


Find the Binary Cross Entropy loss between the two vectors.
You can find the loss functions [here](https://pytorch.org/docs/stable/nn.html).  


In [ ]:
# Binaray Cross entropy loss....


### Multi Layer Perceptron Forward Pass

In [ ]:
# Lets initialise a MLP 
class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.layers = nn.Sequential(
            nn.Linear(2, 2, bias = False), 
            nn.Linear(2, 1, bias = False))
    def forward(self, x):
        return self.layers(x)

In [ ]:
net1 = MLP()
x = torch.rand(2).float()
with torch.no_grad(): out = net1(x)

In [ ]:
print(f'Input to net : {x}')
print('-'*50)
print(f'Layer 0 parameters {net1.layers[0].weight}')
print(f'Layer 1 parameters {net1.layers[1].weight}')
print('-'*50)
print(f'Output : {out}')

Input to net : tensor([0.9391, 0.4167])
--------------------------------------------------
Layer 0 parameters Parameter containing:
tensor([[ 0.1975,  0.6707],
        [ 0.4667, -0.6443]], requires_grad=True)
Layer 1 parameters Parameter containing:
tensor([[-0.6723, -0.3411]], requires_grad=True)
--------------------------------------------------
Output : tensor([-0.3705])


Can you calculate through matrix multiplication ?   
Tip, you can use the torch.matmul function to multiply matrices, or alternatively check [this](https://stackoverflow.com/questions/60275705/how-to-calculate-a-forward-pass-with-matrix-operations-in-pytorch) link for calculating a forward pass. 

In [ ]:
# You can enter your calculations here. 

### Multi Layer Perceptron Forward Pass with bias term
If we add the bias term can you calculate to forward pass now ?

In [ ]:
class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.layers = nn.Sequential(
            nn.Linear(2, 2, bias = True), 
            #nn.ReLU(),
            nn.Linear(2, 1, bias = True))
    def forward(self, x):
        return self.layers(x)

In [ ]:
net2 = MLP()
with torch.no_grad(): out = net2(x)

In [ ]:
print(f'Input to net : {x}')
print('-'*50)
print(f'Layer 0 parameters {net2.layers[0].weight}')
print(f'Layer 0 bias       {net2.layers[0].bias}\n')
print(f'Layer 1 parameters {net2.layers[1].weight}')
print(f'Layer 1 bias       {net2.layers[1].bias}\n')
print('-'*50)
print(f'Output : {out}')

Input to net : tensor([0.9391, 0.4167])
--------------------------------------------------
Layer 0 parameters Parameter containing:
tensor([[ 0.3026, -0.3286],
        [ 0.6938, -0.2992]], requires_grad=True)
Layer 0 bias       Parameter containing:
tensor([0.5303, 0.0084], requires_grad=True)

Layer 1 parameters Parameter containing:
tensor([[-0.3725,  0.3635]], requires_grad=True)
Layer 1 bias       Parameter containing:
tensor([-0.3753], requires_grad=True)

--------------------------------------------------
Output : tensor([-0.4332])


In [ ]:
# You can enter your calculations here. 

### Multi Layer Perceptron Forward Pass with Relu
If we add a RELU activation, can you calculate the forward pass now ?

In [ ]:
class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.layers = nn.Sequential(
            nn.Linear(2, 2, bias = True), 
            nn.ReLU(),
            nn.Linear(2, 1, bias = True))
    def forward(self, x):
        return self.layers(x)

In [ ]:
net3 = MLP()
with torch.no_grad(): out = net3(x)

In [ ]:
print(f'Input to net : {x}')
print('-'*50)
print(f'Layer 0 parameters {net3.layers[0].weight}')
print(f'Layer 0 bias       {net3.layers[0].bias}\n')
print(f'Layer 1 parameters {net3.layers[2].weight}')
print(f'Layer 1 bias       {net3.layers[2].bias}\n')
print('-'*50)
print(f'Output : {out}')

Input to net : tensor([0.9391, 0.4167])
--------------------------------------------------
Layer 0 parameters Parameter containing:
tensor([[ 0.2080, -0.2042],
        [-0.0775, -0.6798]], requires_grad=True)
Layer 0 bias       Parameter containing:
tensor([-0.3371,  0.3837], requires_grad=True)

Layer 1 parameters Parameter containing:
tensor([[-0.1719,  0.7043]], requires_grad=True)
Layer 1 bias       Parameter containing:
tensor([0.5668], requires_grad=True)

--------------------------------------------------
Output : tensor([0.5863])


In [ ]:
# You can enter your calculations here. 